### ISSUE TITLE
Generated colors do not exist

### ISSUE THREAD

**Issue by Immortalin** [RubixCube-Innovations/mantine-theme-builder#10]
Missing colors in theme.ts

<img width="373" alt="image" src="https://github.com/user-attachments/assets/1d555f90-48bb-4558-bdbb-32aaa6e8a745">

**Comment by Immortalin** [comment]
cssVariableResolver also contains a non-existent import 

<img width="518" alt="image" src="https://github.com/user-attachments/assets/d653f679-0717-4dbd-84b0-a2052e5f61a2">

**Comment by Immortalin** [comment]
Incorrect parenthesis placement in generated code:

![image](https://github.com/user-attachments/assets/db7d2989-b1dd-4ae8-b200-554fa9882356)

**Comment by Immortalin** [comment]
Incorrect double var generated 

![image](https://github.com/user-attachments/assets/086df5c9-7834-445b-90ac-970112a05cec)

**Comment by Immortalin** [comment]
![image](https://github.com/user-attachments/assets/f3805796-60fe-4a5e-a9a8-4237ef0d36f3)
Alert box title and close button uses the wrong color

**Comment by Abhishek-S-Lal** [comment]
Thanks for reporting. All the mentioned issues are fixed. Also, the next version is released, which has a lot more updates and theming support for all the components. Please use the latest code from the website.

**Comment by Shadowfita** [comment]
It seems now that the generated theme code is not respecting the primary color that you select on the customizer @Abhishek-S-Lal . 

Keep up the great work!

**Comment by Abhishek-S-Lal** [comment]
@Shadowfita Thanks for reporting. Will fix the issue asap.

**Comment by Shadowfita** [comment]
> @Shadowfita Thanks for reporting. Will fix the issue asap.

Legend.

**Comment by Shadowfita** [comment]
@Abhishek-S-Lal Can confirm, thank you for the speedy fix!

**Comment by Immortalin** [comment]
Random console.log in generated code
![image](https://github.com/user-attachments/assets/aeba13a3-c921-4891-8e1f-58d42c18de6e)
The alert box title and close button color issue is still there.

![image](https://github.com/user-attachments/assets/70f29226-859a-4209-b920-ff7a7e4f3158)

**Comment by Abhishek-S-Lal** [comment]
@Immortalin console.log is removed. 
For a quick fix for alert box and close button, please try specifying the variant and check. 

`<Alert variant="light" title="Alert title">
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. At officiis, quae tempore necessitatibus placeat saepe.
    </Alert>`
    
    Please check the code given in the playground of alert. Will provide a permanent fix soon.

**Comment by Abhishek-S-Lal** [comment]
@Immortalin The issue is fixed. Please check.

**Comment by Immortalin** [comment]
Fix confirmed 👍🏻
