### ISSUE TITLE
Broken Disabled Styling for Button Component in Light and Dark Modes

### ISSUE THREAD

**Issue by AndrejNemec** [RubixCube-Innovations/mantine-theme-builder#11]
There seems to be an issue with the styling of the Button component in its disabled state. In the Playground, the disabled styling works as expected. However, when setting up a new clean project, copying all theme files directly from the website, and using the Button component with `disabled={true}` attribute, the colors are broken in both light and dark modes.

**Reproduction link:** https://stackblitz.com/edit/vitejs-vite-kcdhiwdl?file=src%2FApp.tsx

**Steps to Reproduce**
	1.	Open the provided StackBlitz link.
	2.	Observe the Button component with disabled={true}.
	3.	Note that the colors are broken in both light and dark modes.

**Expected Behavior**
The Button component should maintain consistent styling with correct colors in both light and dark modes when in a disabled state.

**Actual Behavior**
The colors are broken in both light and dark modes when the Button component is disabled.

**Comment by Abhishek-S-Lal** [comment]
Hi @AndrejNemec 
Thanks for reporting. As a quick fix, you can explicitly specify the variant as filled and it will work as expected. 

`<Button variant="filled" onClick={increment} disabled>
        DISABLED BUTTON
      </Button>`
      
      
<img width="365" alt="image" src="https://github.com/user-attachments/assets/150c5b31-a299-4ea4-8183-9e9612fb366e" />

I will fix the default variant issue for all the components very soon.

**Comment by AndrejNemec** [comment]
@Abhishek-S-Lal This issue also occurs with the “gradient” variant of the button. Setting variant="gradient" does not fix the issue, unlike with the variant="filled" prop for the default button.

Link: https://stackblitz.com/edit/vitejs-vite-kcdhiwdl?file=src%2FApp.tsx

**Comment by Abhishek-S-Lal** [comment]
@AndrejNemec Fixed the gradient variant disabled issue. Please copy the latest style.css code from the website
