### ISSUE TITLE
CSSVariablesResolver breaks charts tooltip

### ISSUE THREAD

**Issue by patrik-simunic-cz** [RubixCube-Innovations/mantine-theme-builder#12]
In the `cssVariablesResolver`, the `var(--mantine-color-bright)` seems to be set to the same color as the color scheme - ie. in light mode the `bright` color is set to `var(--mantine-color-white)` and in the dark mode the `bright` color is set to `var(--mantine-color-secondary-9)`.
<br>
<img width="873" alt="CSSVariablesResolver" src="https://github.com/user-attachments/assets/4e7a14f9-edca-49d6-a7c5-5c2a36d9fc5f" />
<br><br>
In Mantine, the bright color has contrast against the current color scheme (black in light mode, white in dark mode). In this theme builder, the bright color is the opposite (white in light mode, black in dark mode).

I'm not sure if this is required anywhere by this theme builder, but in any case, this breaks a tooltip in the `@mantine/charts` library. Title and series values are set to the `var(--mantine-color-bright)` color variable. So when this theme builder is applied, most of the charts tooltip becomes invisible (white text on white bg / black text on black bg).

Have a look (first image is from the official Mantine docs and second image is from [mantinehub.com/playground](https://mantinehub.com/playground)):
<br>
<img width="1495" alt="Official Mantine docs" src="https://github.com/user-attachments/assets/825c92f1-a09e-4e10-8a86-616f70b80c20" />

<img width="1495" alt="mantinehub.com/playground" src="https://github.com/user-attachments/assets/2644d3cb-2cca-4df9-8fe8-98c4314bf3bf" />
<br><br>
PS: Awesome work! ❤️ I've been looking for some nice Mantine themes for a long time, and this awesome 😊 Thank you for your work!

**Comment by Abhishek-S-Lal** [comment]
@patrik-simunic-cz Thanks for pointing out. I will try to make the variable align with the mantine theming approach.

**Comment by Abhishek-S-Lal** [comment]
@patrik-simunic-cz "--mantine-color-bright" will now use default colors from mantine(black color in light mode and white color in dark mode). I have updated the theme file to replace "--mantine-color-bright". Also updated border color in chart tooltips.

**Comment by patrik-simunic-cz** [comment]
@Abhishek-S-Lal Wow, that was blazingly fast issue resolution 🤯😊 Thank you, looks/works amazing now! ❤️
