### ISSUE TITLE
github page usage

### ISSUE THREAD

**Issue by auronvila** [RubixCube-Innovations/mantine-theme-builder#14]
hey guys I recently was checking the theme builder and I was amazed by the work. I think it would be so good if the project would have a showcase which is hosted in github pages (free of use) and anyone that comes to check the theme builder will have a chance of trying it.

**Comment by Abhishek-S-Lal** [comment]
Hi @auronvila,

Thank you for your suggestion! I wanted to let you know that this project is already hosted and live at [mantinehub.com](https://mantinehub.com/) and also at [mantine-theme-builder.netlify.app](https://mantine-theme-builder.netlify.app/).

Additionally, the link to the live app is mentioned on the GitHub repository's homepage for easy access.

If you're suggesting something different, could you please clarify? I’d be happy to understand and sort it out.

**Comment by auronvila** [comment]
I didn't saw the preview in the documentation thank you for clarification, I am planning to put the preview in my mantine dashboard template's documentation.
