### ISSUE TITLE
Letter spacing for headers

### ISSUE THREAD

**Issue by matthiasfeist** [RubixCube-Innovations/mantine-theme-builder#2]
Headings in shadcn use the tailwind class`tracking-tight`. For example the heading in a dialog.
That's currently missing from all the h1...h6 styles :)

**Comment by Abhishek-S-Lal** [comment]
The style of tracking-tight has been applied to all Title components. Use the updated style.css from the mantine-theme-builder website..

**Comment by matthiasfeist** [comment]
Awesome! thanks for fixing. 🥳 
One place where this is not applied (because it's technically not a title-component) is the header of the modal.
