### ISSUE TITLE
Great Work!

### ISSUE THREAD

**Issue by Shadowfita** [RubixCube-Innovations/mantine-theme-builder#6]
It's great to see someone create a resource like this to compliment mantine.dev. I've thought for some time now that this kind of tool would be extremely valuable. Very excited that it's finally here and done-so in a very intuitive way. Great work.

**Comment by Abhishek-S-Lal** [comment]
Thank you so much for your kind words and support! 🎉 It’s great to hear that you find the tool valuable and intuitive.

If you don’t mind, could you share this feedback in [this Mantine discussion thread](https://github.com/orgs/mantinedev/discussions/7056) where our project is showcased? It would mean a lot to us and help the broader community discover and benefit from the tool.

We’re actively working on enhancing the tool and adding new features, so please check back regularly. Your feedback is invaluable—thank you again for your encouragement! 😊

**Comment by Shadowfita** [comment]
@Abhishek-S-Lal of course! I've left a comment. Great work once again, I'm excited to see how this project progresses, especially seeing how much has been done in such a short time.
