### ISSUE TITLE
Alert color is broken

### ISSUE THREAD

**Issue by Immortalin** [RubixCube-Innovations/mantine-theme-builder#8]
HI, using the Shadcn slate colored theme generated by the builder breaks the Mantine alert component. Setting the background color via the mantine props no longer works. I think the cssVariableResolver needs to be updated.

https://mantine.dev/core/alert/

**Comment by Abhishek-S-Lal** [comment]
@Immortalin We are working on it. This issue will be fixed in the next major release that is scheduled for this weekend. If you need a quick fix, let us know, we can help you.

**Comment by Abhishek-S-Lal** [comment]
The issue is fixed in the latest release. Please use the new theme code from the website. Theming of all components is completed now.
