### ISSUE TITLE
[BUG] Typescript Error : 'string[]' is not assignable to type 'readonly  string[]'

### ISSUE THREAD

**Issue by NakulPrasad** [RubixCube-Innovations/mantine-theme-builder#9]
I recently tried genrating theme for shadcdn with minor tweaks, got following error in 'theme.ts'
```
Type 'string[]' is not assignable to type 'readonly [string, string, string, string, string, string, string, string, string, string, ...string[]]'.
  Source provides no match for required element at position 0 in target.ts(2322)
(property) zinc: string[]
```

**Comment by NakulPrasad** [comment]
> Annotate the array with type `MantineColorsTuple`, it will fix the problem.

Thanks it fixes the error.

**Comment by Abhishek-S-Lal** [comment]
@NakulPrasad Please use the latest theme code from the website. This issue is fixed there as well. Also, the theming for all the components is available in the new version.
